# Generated by Django 5.1.1 on 2024-09-23 19:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem')),
                ('post_date', models.DateField(verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
